### ISSUE TITLE
Battery Charge Current

### ISSUE THREAD

**Issue by davlast** [ned-kelly/docker-voltronic-homeassistant#12]
Hi
Any idea why my battery charge current is showing 0
sensor.voltronic_battery_charge_current

![image](https://user-images.githubusercontent.com/24844893/74259535-b88fec00-4d00-11ea-97e0-a3db8396a948.png)

Have an Axpert 1kva mppt inverter

seems like everything else is working

thanks in advance

**Comment by fjmalan** [comment]
@davlast , how did you manage to solve this ?
