### ISSUE TITLE
Run on Raspberry Pi

### ISSUE THREAD

**Issue by markve-sa** [ned-kelly/docker-voltronic-homeassistant#2]

**Comment by md7automation** [comment]
Hi there,  i am trying to connect the application to the inverter using docker and USB direct (usb > usb) but i cannot see /dev/hidraw0. The actual USB link does work on the standard MPP solar watch power App. /dev/bus/usb/001/006 is the closest i could get to, but that doesn't work. Could you help ? Thanks in advance
