### ISSUE TITLE
Unable to detect Mosquitto in HA

### ISSUE THREAD

**Issue by eikcamils** [ned-kelly/docker-voltronic-homeassistant#21]
I got a 2 raspberry pi. The first one is running docker getting data from inverter, the second is running HA it seams that is able to read data but is not automatically detected. 

I have this in logs...
![photo_2020-05-17_07-55-51](https://user-images.githubusercontent.com/65504578/82155345-80a2c280-9874-11ea-81ff-71df20a35aad.jpg)

**Comment by andrea1388** [comment]
Try to enable mqtt discovery in configuration.yaml

mqtt:
  broker: 127.0.0.1
  discovery: true

**Comment by eikcamils** [comment]
> Try to enable mqtt discovery in configuration.yaml
> 
> mqtt:
> broker: 127.0.0.1
> discovery: true

It works! Andrea thank you so so much!
