### ISSUE TITLE
docker doesn't correctly identify the target platform

### ISSUE THREAD

**Issue by CloudyChris** [ned-kelly/docker-voltronic-homeassistant#41]
I can't seem to set up docker... upon docker-compose up I get

![185314398_214828676837809_1856847673272422437_n](https://user-images.githubusercontent.com/8339678/117971313-6342f000-b332-11eb-8367-03121bf9a6ee.jpg)

And trying to uncomment the build flag in the yml returns the same "wrong target platform" warning.
It wasn't very clear how you specify the target platform in your set-up tutorial / docs.
I saw a --platform flag, but I don't find where to put it. 
Any help would be appreciated

**Comment by VolkArr** [comment]
Try to use: docker-compose build
This command will install debian and all will be right.
