### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by manju850** [ned-kelly/docker-voltronic-homeassistant#6]
Hi Ned
Sorry for troubling. I am newbie I dnt know how to run this on my RB p1. could you please just put basic step to run this. 
Sorry again
Thanks
Manjula

**Comment by ned-kelly** [comment]
Hi @manju850 

You just need to install [Docker](https://www.docker.com/get-started) and [Docker Compose](https://docs.docker.com/compose/install/) on your Pi, and then follow the instructions in the "Configuration & Standing Up" section of the Readme file...

If you're running the first edition of the Pi you'll probably find Docker support sparse - so your best bet is to run the Hypriot build - which has Excellent docker support for the older PI's  https://blog.hypriot.com/
