### ISSUE TITLE
Help with Grafana dashboard

### ISSUE THREAD

**Issue by andriuskr** [ned-kelly/docker-voltronic-homeassistant#80]
I have managed to send data form inverter to influx db. But with grafana i am tottal noob and when inporting grafana dashboard it does not show any data. 
What i possibly do wrong ?

**Comment by ned-kelly** [comment]
Hi there,

I think it's probably best you post an issue on the grafana forums if you're having issues pulling data from influxdb to grafana as this is not directly related to the voltronic inverter poller.

Cheers,
