### ISSUE TITLE
Data stopped from the inverter - Voltronic Axpert MKS IV 5.6kW 

### ISSUE THREAD

**Issue by amagr0** [ned-kelly/docker-voltronic-homeassistant#81]
Hello, 

After some hours of working well, the data simply stopped from being send from the inverter.
What could cause this issue?

Inverter: Voltronic Axpert MKS IV 5.6kW 

Configuration: 
- device=/dev/hidraw0
- run_interval=120
- qpiri=103
- qpiws=40
- qmod=5
- qpigs=110

![image](https://user-images.githubusercontent.com/12901952/172331878-a9a046b0-cd3e-4a4b-92b7-55e8179ee2fd.png)

....

There's also some issue with displayed value - voltronic_Battery_redischarge_voltage

![image](https://user-images.githubusercontent.com/12901952/172332152-7dbee7d8-b808-4c7b-bfae-d665bb706d94.png)

Thanks,
AMagro

**Comment by ned-kelly** [comment]
Hi there,

This sounds like possibly there may be a bad earth or something that's effecting the data transfer to the inverter.

Does rebooting fix it?
