### ISSUE TITLE
Ubuntu Server LTS 22.04 error starting docker-compose 

### ISSUE THREAD

**Issue by oliveritech** [ned-kelly/docker-voltronic-homeassistant#84]
Hello and tank you to ned-kelly and BionicWeb for the hard work and to make this public. I'm new to Linux and after geting everithing setup when I run the command  docker-compose up -d 
is returning with the following error:

oliveritech@max-7200-datalogger:/opt/ha-inverter-mqtt-agent$ sudo docker-compose up -d
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml

I can't find a possible solution, even running the command in different directory; please help 
Thank you

**Comment by ned-kelly** [comment]
Please try and manually specify the filename:

`cd /opt/ha-inverter-mqtt-agent  && docker-compose -f docker-compose.yml up -d`
